### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mguthaus** [vsdip/vsdsram_sky130#1]
Hi,

These files (especially the tech.py) were taken from OpenRAM, which is ok, but you need to include our copyright which is the restriction of the BSD license. Thanks!

Matt

**Comment by ShonTaware** [comment]
Hi, 
We have included the OpenRAM copyright BSD license to our project. 
[License](https://github.com/vsdip/vsdsram_sky130/blob/main/LICENSE)

Thank you!
Shon
