### ISSUE TITLE
openRAM stuck 

### ISSUE THREAD

**Issue by ratul619** [vsdip/vsdsram_sky130#2]
Hi , 

What is the typical runtime , seems the output is stuck for ~15mins : 

 python3 $OPENRAM_HOME/openram.py myconfig_sky130.py

WARNING: file globals.py: line 182: Failed to find coverage installation. This can be installed with pip3 install coverage
|==============================================================================|
|=========                      OpenRAM v1.1.19                       =========|
|=========                                                            =========|
|=========               VLSI Design and Automation Lab               =========|
|=========        Computer Science and Engineering Department         =========|
|=========            University of California Santa Cruz             =========|
|=========                                                            =========|
|=========          Usage help: openram-user-group@ucsc.edu           =========|
|=========        Development help: openram-dev-group@ucsc.edu        =========|
|=========        Temp dir: /tmp/openram_ratul619_13146_temp/         =========|
|=========                See LICENSE for license info                =========|
|==============================================================================|
** Start: 03/01/2022 11:47:57
Technology: sky130A
Total size: 32768 bits
Word size: 32
Words: 1024
Banks: 1
Write size: None
RW ports: 1
R-only ports: 0
W-only ports: 0
DRC/LVS/PEX is only run on the top-level design to save run-time (inline_lvsdrc=True to do inline checking).
DRC/LVS/PEX is disabled (check_lvsdrc=True to enable).
Characterization is disabled (using analytical delay models) (analytical_delay=False to simulate).
Words per row: 8
Output files are: 
/home/ratul619/IIT_study_VM/IPs/vsdsram_sky130/OpenRAM/temp/sram_32_1024_sky130A.lvs
/home/ratul619/IIT_study_VM/IPs/vsdsram_sky130/OpenRAM/temp/sram_32_1024_sky130A.sp
/home/ratul619/IIT_study_VM/IPs/vsdsram_sky130/OpenRAM/temp/sram_32_1024_sky130A.v
/home/ratul619/IIT_study_VM/IPs/vsdsram_sky130/OpenRAM/temp/sram_32_1024_sky130A.lib
/home/ratul619/IIT_study_VM/IPs/vsdsram_sky130/OpenRAM/temp/sram_32_1024_sky130A.py
/home/ratul619/IIT_study_VM/IPs/vsdsram_sky130/OpenRAM/temp/sram_32_1024_sky130A.html
/home/ratul619/IIT_study_VM/IPs/vsdsram_sky130/OpenRAM/temp/sram_32_1024_sky130A.log
/home/ratul619/IIT_study_VM/IPs/vsdsram_sky130/OpenRAM/temp/sram_32_1024_sky130A.lef
/home/ratul619/IIT_study_VM/IPs/vsdsram_sky130/OpenRAM/temp/sram_32_1024_sky130A.gds
** Submodules: 39.8 seconds
** Placement: 0.1 seconds
Thanks

**Comment by ShonTaware** [comment]
The runtime depends multiple factors. I am mentioning few:

1. Total size of memory (word size * words)
    - For a 32 x 1024, it takes me around 90+ minutes
2. Performance of your linux machine
    - Generation of same memory size takes significantly different amount of time on two different machines

**Comment by ratul619** [comment]
For a 32 x 1024, it takes me around 90+ minutes  :: Ok so i should wait .. Tried on smaller _2.py file --> seems generating output , so flow setup looks fine... Only runtime issue
